project:
  type: website
  output-dir: docs

website:
  title: "Pragya Singh"
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false



